// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tools.automation.bean;

import org.springframework.beans.factory.annotation.Configurable;
import tools.automation.bean.PeiTemplateCategory;

privileged aspect PeiTemplateCategory_Roo_Configurable {
    
    declare @type: PeiTemplateCategory: @Configurable;
    
}
