// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package tools.automation.bean;

import org.springframework.beans.factory.annotation.Configurable;
import tools.automation.bean.PmsmartLobLevel4;

privileged aspect PmsmartLobLevel4_Roo_Configurable {
    
    declare @type: PmsmartLobLevel4: @Configurable;
    
}
